### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by dextok** [takeern/witMarket#1]
能否共享数据库SQL文件供测试，谢谢

**Comment by takeern** [comment]
可以的 你要哪配置文件？还是具体数据？

**Comment by dextok** [comment]
我需要建表的SQL语句以便了解各个表的结构 @takeern

**Comment by takeern** [comment]
我把SQL 文件发出来吧，有结构和数据，你直接导入就可以了！

**Comment by takeern** [comment]
我把SQL 文件发到住目录sql文件夹下面
